#!/usr/bin/env python3
from __future__ import annotations

import glob
import json
import re
import subprocess
import sys
from pathlib import Path


THREAD_COUNT = 256
A_SIZE = 128
B_SIZE = 128
C_SIZE = 128
SFA_SIZE = 128
SFB_SIZE = 128


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def find_include_roots(root: Path) -> list[Path]:
    candidates = [
        root / ".venv-trtllm/lib/python3.12/site-packages/flashinfer/data/cutlass/include",
    ]
    candidates.extend(
        Path(path)
        for path in glob.glob(
            str(Path.home() / ".cache/uv/archive-v0/*/tensorrt_llm/deep_gemm/include")
        )
    )
    return [path for path in candidates if path.exists()]


def compile_probe(root: Path, probe: Path, binary: Path) -> None:
    include_roots = find_include_roots(root)
    if not include_roots:
        raise RuntimeError("Unable to locate a CUTLASS/CUTE include root for the P15 probe")
    cmd = ["nvcc", "-std=c++20", str(probe), "-O0", "-g", "-o", str(binary)]
    for include_root in include_roots:
        cmd.extend(["-I", str(include_root)])
    cmd.extend(["-I", "/usr/local/cuda/include"])
    subprocess.run(cmd, cwd=root, check=True)


def parse_probe_output(text: str) -> dict:
    meta: dict[str, int] = {}
    data = {
        "A": [[None] * A_SIZE for _ in range(THREAD_COUNT)],
        "B": [[None] * B_SIZE for _ in range(THREAD_COUNT)],
        "C": [[None] * C_SIZE for _ in range(THREAD_COUNT)],
        "SFA": [[None] * SFA_SIZE for _ in range(THREAD_COUNT)],
        "SFB": [[None] * SFB_SIZE for _ in range(THREAD_COUNT)],
    }
    current_thread: int | None = None

    meta_re = re.compile(r"^META\s+(\w+)\s+_?(\d+)$")
    thread_re = re.compile(r"^THREAD\s+(\d+)$")
    coord2_re = re.compile(r"^(A|B|C|SFB)\s+(\d+)\s+(\d+)\s+(\d+)$")
    coord3_re = re.compile(r"^(SFA)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)$")

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if match := meta_re.match(line):
            meta[match.group(1)] = int(match.group(2))
            continue
        if match := thread_re.match(line):
            current_thread = int(match.group(1))
            continue
        if current_thread is None:
            raise RuntimeError(f"Encountered payload before thread header: {line}")
        if match := coord2_re.match(line):
            tag, idx, a, b = match.groups()
            data[tag][current_thread][int(idx)] = [int(a), int(b)]
            continue
        if match := coord3_re.match(line):
            tag, idx, a, b, c = match.groups()
            data[tag][current_thread][int(idx)] = [int(a), int(b), int(c)]
            continue
        raise RuntimeError(f"Unrecognized probe line: {line}")

    expected_meta = {
        "threads": THREAD_COUNT,
        "a_copy_size": A_SIZE,
        "b_copy_size": B_SIZE,
        "c_store_size": C_SIZE,
        "sfa_stage0_size": SFA_SIZE,
        "sfb_stage0_size": SFB_SIZE,
    }
    for key, expected in expected_meta.items():
        actual = meta.get(key)
        if actual != expected:
            raise RuntimeError(f"Probe meta mismatch for {key}: expected {expected}, got {actual}")

    for tag, threads in data.items():
        for thread_idx, coords in enumerate(threads):
            missing = [idx for idx, coord in enumerate(coords) if coord is None]
            if missing:
                raise RuntimeError(f"Missing {tag} coords for thread {thread_idx}: {missing[:8]}")
    return {"meta": meta, "data": data}


def emit_inc(parsed: dict) -> str:
    meta = parsed["meta"]
    data = parsed["data"]

    def emit_coord2_block(name: str, tag: str) -> list[str]:
        lines = [
            f"inline constexpr P15Coord2 {name}[kP15ThreadCount][kP15{tag}CoordCount] = {{"
        ]
        for thread in data[tag]:
            coords = ", ".join(f"{{{row}, {col}}}" for row, col in thread)
            lines.append(f"    {{{coords}}},")
        lines.append("};")
        return lines

    def emit_sfa_block() -> list[str]:
        lines = [
            "inline constexpr P15ScaleACoord kP15ScaleAStage0[kP15ThreadCount][kP15ScaleAStage0Count] = {"
        ]
        for thread in data["SFA"]:
            coords = ", ".join(f"{{{row}, {scale_idx}, {col}}}" for row, scale_idx, col in thread)
            lines.append(f"    {{{coords}}},")
        lines.append("};")
        return lines

    lines = [
        "// Generated by proj-2026-04-05-1704/generate_p15_probe_tables.py",
        "// from proj-2026-04-05-1704/trt_p15_full_thread_contract_dump.cu.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "#if defined(__CUDACC__)",
        "#define NEMOTRON_P15_PROBE_HD __host__ __device__",
        "#else",
        "#define NEMOTRON_P15_PROBE_HD",
        "#endif",
        "",
        "namespace nemotron::p15_probe_generated {",
        "",
        "struct P15Coord2 {",
        "  std::uint16_t row;",
        "  std::uint16_t col;",
        "};",
        "",
        "struct P15ScaleACoord {",
        "  std::uint16_t row;",
        "  std::uint16_t scale_idx;",
        "  std::uint16_t col;",
        "};",
        "",
        f"inline constexpr int kP15ThreadCount = {meta['threads']};",
        f"inline constexpr int kP15Stages = {meta['stages']};",
        f"inline constexpr int kP15ACoordCount = {meta['a_copy_size']};",
        f"inline constexpr int kP15BCoordCount = {meta['b_copy_size']};",
        f"inline constexpr int kP15CCoordCount = {meta['c_store_size']};",
        f"inline constexpr int kP15ScaleAStage0Count = {meta['sfa_stage0_size']};",
        f"inline constexpr int kP15ScaleBStage0Count = {meta['sfb_stage0_size']};",
        "",
    ]
    lines.extend(emit_coord2_block("kP15DenseACopyCoords", "A"))
    lines.append("")
    lines.extend(emit_coord2_block("kP15DenseBCopyCoords", "B"))
    lines.append("")
    lines.extend(emit_coord2_block("kP15DenseStoreCoords", "C"))
    lines.append("")
    lines.extend(emit_sfa_block())
    lines.append("")
    lines.extend(emit_coord2_block("kP15ScaleBStage0Coords", "SFB"))
    lines.extend(["", "}  // namespace nemotron::p15_probe_generated", ""])
    return "\n".join(lines)


def emit_compact_header(parsed: dict) -> str:
    meta = parsed["meta"]
    data = parsed["data"]

    def emit_coord2_base(name: str, tag: str) -> list[str]:
        count_symbol = (
            "kP15ScaleBStage0Count" if tag == "SFB" else f"kP15{tag}CoordCount"
        )
        lines = [f"inline constexpr P15Coord2 {name}[kP15LaneCount][{count_symbol}] = {{"]
        for lane in range(32):
            coords = ", ".join(
                f"{{{row}, {col}}}" for row, col in data[tag][lane]
            )
            lines.append(f"    {{{coords}}},")
        lines.append("};")
        return lines

    def emit_sfa_base() -> list[str]:
        lines = [
            "inline constexpr P15ScaleACoord kP15ScaleAStage0Base[kP15LaneCount][kP15ScaleAStage0Count] = {"
        ]
        for lane in range(32):
            coords = ", ".join(
                f"{{{row}, {scale_idx}, {col}}}"
                for row, scale_idx, col in data["SFA"][lane]
            )
            lines.append(f"    {{{coords}}},")
        lines.append("};")
        return lines

    def compute_constant_delta(tag: str, lane: int, src: int, component: int) -> int:
        base = data[tag][lane]
        other = data[tag][src]
        deltas = {other[i][component] - base[i][component] for i in range(len(base))}
        if len(deltas) != 1:
            raise RuntimeError(f"{tag} delta for lane={lane} src={src} component={component} is not constant: {sorted(deltas)}")
        return next(iter(deltas))

    a_row_per_warp = compute_constant_delta("A", 0, 32, 0)
    a_row_upper_half = compute_constant_delta("A", 0, 128, 0)
    a_col_per_warp = compute_constant_delta("A", 0, 32, 1)
    a_col_upper_half = compute_constant_delta("A", 0, 128, 1)
    b_row_per_warp = compute_constant_delta("B", 0, 32, 0)
    b_row_upper_half = compute_constant_delta("B", 0, 128, 0)
    b_col_per_warp = compute_constant_delta("B", 0, 32, 1)
    b_col_upper_half = compute_constant_delta("B", 0, 128, 1)
    c_row_per_warp = compute_constant_delta("C", 0, 32, 0)
    c_row_upper_half = compute_constant_delta("C", 0, 128, 0)
    c_col_per_warp = compute_constant_delta("C", 0, 32, 1)
    c_col_upper_half = compute_constant_delta("C", 0, 128, 1)
    sfa_row_per_warp = compute_constant_delta("SFA", 0, 32, 0)
    sfa_row_upper_half = compute_constant_delta("SFA", 0, 128, 0)
    sfa_scale_per_warp = compute_constant_delta("SFA", 0, 32, 1)
    sfa_scale_upper_half = compute_constant_delta("SFA", 0, 128, 1)
    sfa_col_per_warp = compute_constant_delta("SFA", 0, 32, 2)
    sfa_col_upper_half = compute_constant_delta("SFA", 0, 128, 2)
    sfb_row_per_warp = compute_constant_delta("SFB", 0, 32, 0)
    sfb_row_upper_half = compute_constant_delta("SFB", 0, 128, 0)
    sfb_col_per_warp = compute_constant_delta("SFB", 0, 32, 1)
    sfb_col_upper_half = compute_constant_delta("SFB", 0, 128, 1)

    lines = [
        "// Generated by proj-2026-04-05-1704/generate_p15_probe_tables.py",
        "// from proj-2026-04-05-1704/trt_p15_full_thread_contract_dump.cu.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "#if defined(__CUDACC__)",
        "#define NEMOTRON_P15_PROBE_HD __host__ __device__",
        "#else",
        "#define NEMOTRON_P15_PROBE_HD",
        "#endif",
        "",
        "namespace nemotron::p15_probe_generated {",
        "",
        "struct P15Coord2 {",
        "  std::uint16_t row;",
        "  std::uint16_t col;",
        "};",
        "",
        "struct P15ScaleACoord {",
        "  std::uint16_t row;",
        "  std::uint16_t scale_idx;",
        "  std::uint16_t col;",
        "};",
        "",
        f"inline constexpr int kP15ThreadCount = {meta['threads']};",
        "inline constexpr int kP15LaneCount = 32;",
        f"inline constexpr int kP15Stages = {meta['stages']};",
        f"inline constexpr int kP15ACoordCount = {meta['a_copy_size']};",
        f"inline constexpr int kP15BCoordCount = {meta['b_copy_size']};",
        f"inline constexpr int kP15CCoordCount = {meta['c_store_size']};",
        f"inline constexpr int kP15ScaleAStage0Count = {meta['sfa_stage0_size']};",
        f"inline constexpr int kP15ScaleBStage0Count = {meta['sfb_stage0_size']};",
        "",
        f"inline constexpr int kP15A_RowPerWarpMod4 = {a_row_per_warp};",
        f"inline constexpr int kP15A_RowUpperHalf = {a_row_upper_half};",
        f"inline constexpr int kP15A_ColPerWarpMod4 = {a_col_per_warp};",
        f"inline constexpr int kP15A_ColUpperHalf = {a_col_upper_half};",
        f"inline constexpr int kP15B_RowPerWarpMod4 = {b_row_per_warp};",
        f"inline constexpr int kP15B_RowUpperHalf = {b_row_upper_half};",
        f"inline constexpr int kP15B_ColPerWarpMod4 = {b_col_per_warp};",
        f"inline constexpr int kP15B_ColUpperHalf = {b_col_upper_half};",
        f"inline constexpr int kP15C_RowPerWarpMod4 = {c_row_per_warp};",
        f"inline constexpr int kP15C_RowUpperHalf = {c_row_upper_half};",
        f"inline constexpr int kP15C_ColPerWarpMod4 = {c_col_per_warp};",
        f"inline constexpr int kP15C_ColUpperHalf = {c_col_upper_half};",
        f"inline constexpr int kP15SFA_RowPerWarpMod4 = {sfa_row_per_warp};",
        f"inline constexpr int kP15SFA_RowUpperHalf = {sfa_row_upper_half};",
        f"inline constexpr int kP15SFA_ScalePerWarpMod4 = {sfa_scale_per_warp};",
        f"inline constexpr int kP15SFA_ScaleUpperHalf = {sfa_scale_upper_half};",
        f"inline constexpr int kP15SFA_ColPerWarpMod4 = {sfa_col_per_warp};",
        f"inline constexpr int kP15SFA_ColUpperHalf = {sfa_col_upper_half};",
        f"inline constexpr int kP15SFB_RowPerWarpMod4 = {sfb_row_per_warp};",
        f"inline constexpr int kP15SFB_RowUpperHalf = {sfb_row_upper_half};",
        f"inline constexpr int kP15SFB_ColPerWarpMod4 = {sfb_col_per_warp};",
        f"inline constexpr int kP15SFB_ColUpperHalf = {sfb_col_upper_half};",
        "",
    ]
    lines.extend(emit_coord2_base("kP15DenseACopyBase", "A"))
    lines.append("")
    lines.extend(emit_coord2_base("kP15DenseBCopyBase", "B"))
    lines.append("")
    lines.extend(emit_coord2_base("kP15DenseStoreBase", "C"))
    lines.append("")
    lines.extend(emit_sfa_base())
    lines.append("")
    lines.extend(emit_coord2_base("kP15ScaleBStage0Base", "SFB"))
    lines.extend([
        "",
        "NEMOTRON_P15_PROBE_HD constexpr int P15WarpMod4(int thread_idx) { return (thread_idx >> 5) & 0x3; }",
        "NEMOTRON_P15_PROBE_HD constexpr int P15WarpUpperHalf(int thread_idx) { return thread_idx >> 7; }",
        "",
        "NEMOTRON_P15_PROBE_HD constexpr P15Coord2 GetDenseACopyCoord(int thread_idx, int logical_index) {",
        "  const auto base = kP15DenseACopyBase[thread_idx & 31][logical_index];",
        "  return {",
        "      static_cast<std::uint16_t>(base.row + P15WarpMod4(thread_idx) * kP15A_RowPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15A_RowUpperHalf),",
        "      static_cast<std::uint16_t>(base.col + P15WarpMod4(thread_idx) * kP15A_ColPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15A_ColUpperHalf),",
        "  };",
        "}",
        "",
        "NEMOTRON_P15_PROBE_HD constexpr P15Coord2 GetDenseBCopyCoord(int thread_idx, int logical_index) {",
        "  const auto base = kP15DenseBCopyBase[thread_idx & 31][logical_index];",
        "  return {",
        "      static_cast<std::uint16_t>(base.row + P15WarpMod4(thread_idx) * kP15B_RowPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15B_RowUpperHalf),",
        "      static_cast<std::uint16_t>(base.col + P15WarpMod4(thread_idx) * kP15B_ColPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15B_ColUpperHalf),",
        "  };",
        "}",
        "",
        "NEMOTRON_P15_PROBE_HD constexpr P15Coord2 GetDenseStoreCoord(int thread_idx, int logical_index) {",
        "  const auto base = kP15DenseStoreBase[thread_idx & 31][logical_index];",
        "  return {",
        "      static_cast<std::uint16_t>(base.row + P15WarpMod4(thread_idx) * kP15C_RowPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15C_RowUpperHalf),",
        "      static_cast<std::uint16_t>(base.col + P15WarpMod4(thread_idx) * kP15C_ColPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15C_ColUpperHalf),",
        "  };",
        "}",
        "",
        "NEMOTRON_P15_PROBE_HD constexpr P15ScaleACoord GetScaleAStage0Coord(int thread_idx, int logical_index) {",
        "  const auto base = kP15ScaleAStage0Base[thread_idx & 31][logical_index];",
        "  return {",
        "      static_cast<std::uint16_t>(base.row + P15WarpMod4(thread_idx) * kP15SFA_RowPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15SFA_RowUpperHalf),",
        "      static_cast<std::uint16_t>(base.scale_idx + P15WarpMod4(thread_idx) * kP15SFA_ScalePerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15SFA_ScaleUpperHalf),",
        "      static_cast<std::uint16_t>(base.col + P15WarpMod4(thread_idx) * kP15SFA_ColPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15SFA_ColUpperHalf),",
        "  };",
        "}",
        "",
        "NEMOTRON_P15_PROBE_HD constexpr P15Coord2 GetScaleBStage0Coord(int thread_idx, int logical_index) {",
        "  const auto base = kP15ScaleBStage0Base[thread_idx & 31][logical_index];",
        "  return {",
        "      static_cast<std::uint16_t>(base.row + P15WarpMod4(thread_idx) * kP15SFB_RowPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15SFB_RowUpperHalf),",
        "      static_cast<std::uint16_t>(base.col + P15WarpMod4(thread_idx) * kP15SFB_ColPerWarpMod4 + P15WarpUpperHalf(thread_idx) * kP15SFB_ColUpperHalf),",
        "  };",
        "}",
        "",
        "}  // namespace nemotron::p15_probe_generated",
        "",
        "#undef NEMOTRON_P15_PROBE_HD",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    root = repo_root()
    probe = Path(__file__).with_name("trt_p15_full_thread_contract_dump.cu")
    artifacts_tmp = root / "artifacts/tmp"
    artifacts_bench = root / "artifacts/benchmarks"
    artifacts_tmp.mkdir(parents=True, exist_ok=True)
    artifacts_bench.mkdir(parents=True, exist_ok=True)
    binary = artifacts_tmp / "trt_p15_full_thread_contract_dump_nvcc"
    log_path = artifacts_bench / "trt_p15_full_thread_contract_dump_latest.log"
    json_path = artifacts_tmp / "trt_p15_probe_contract.json"
    inc_path = artifacts_tmp / "trt_p15_probe_generated.inc"
    header_path = root / "runtime/include/nemotron/p15_probe_generated.h"

    compile_probe(root, probe, binary)
    output = subprocess.run(
        [str(binary)],
        cwd=root,
        check=True,
        text=True,
        capture_output=True,
    ).stdout

    log_path.write_text(output)
    parsed = parse_probe_output(output)
    json_path.write_text(json.dumps(parsed, indent=2))
    inc_path.write_text(emit_inc(parsed))
    header_path.write_text(emit_compact_header(parsed))

    print(f"Wrote {log_path}")
    print(f"Wrote {json_path}")
    print(f"Wrote {inc_path}")
    print(f"Wrote {header_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
